### PR TITLE
Tests for path integral methods

### PR DESCRIPTION
**Pull request by chemicalfiend**
Implemented some unit tests for the path integral methods in QuantumDynamics.jl . Currently tests whether QuAPI, TEMPO, QCPI, TTM and HEOM run. Tests are implemented based on the existing examples.

Keeping this as a draft PR for now so that we can add a couple of numerical tests if required.

### CODE REVIEW

**Comment by amartyabose** [comment]
Can we remove the plots dependency? I just added a pyplot dependency.

Also regarding the tests ---- since these are tests of entire methods, we should probably run and verify the results and compare with the stored correct answers.  What do you think?  Right now, as the pull request as it, all we are testing is whether the code is running or not.  Let me know your thoughts.

**Comment by chemicalfiend** [comment]
Yep, removed the plots dependency. I was using that to test a couple of scripts and forgot to remove it. Sure I can test it with stored answers. Do you think it's a good idea to just run the test cases and then copy the RDM values for comparison or do you feel there are better ways to test numerically?

**Comment by amartyabose** [comment]
I am in the process of adding some very basic tests using data generated from a different C++ code that I had lying around.  The trouble is that the package and my ancient code converge differently beyond memory.  But I'm trying to put in some preliminary tests: at least things that test the codes quite thoroughly within memory and then we'll have to figure some way of doing the iterative regime.

Look at my new commits and tell me what you feel.

Also, on second thought I have removed any dependence on plotting software. The reasoning for this is that a user of the package should be free to choose their own plotting routines. The software is not opinionated about that. Let's make the tests free of any plotting function.  (Later we might figure out some way of using PyPlot.jl or Plots.jl as an optional dependency.)

**Comment by chemicalfiend** [comment]
Sure, I think plotting dependencies aren't required.

Regarding numerical tests, I think checking the operation of QuantumDynamics.jl against existing answers from other software is a good idea. I could also add a couple of tests against data obtained from Makri's recently released PathSum package, if you think it's worth doing, but I'm not sure it implements exactly the same methods.

**Comment by amartyabose** [comment]
Yes, absolutely, including tests against PathSum would be wonderful.  I think Nancy has got basic QuAPI, her new SMatPI method, and some others.  Check how I included the tests for reference.

If you are interested, I would like some help in benchmarking the code and may be improving the run-time if you see something is slow.  Precompiling ITensor seems to be a pain in Julia.  It always takes some time.

**Comment by chemicalfiend** [comment]
Hi, I haven't had time to look into the Unitful integration I mentioned in the issue or the other numerical tests yet. I'm marking this PR as open for review to get things moving and will add more tests and integrations along the way. I'm excited to keep working with this package!

**Comment by amartyabose** [comment]
Hey,

Sorry it took me forever to get back to this.  Did you pull the additions that I have mentioned and checked if that works?  It seems like we are testing the same things for most part.  The only extra thing that I see you are doing is checking that you are getting results for the FMO case.

I am not sure how to use the FMO case as a test.  It would take long-ish to run...  Any thoughts?

Best,
Amartya

**Comment by amartyabose** [comment]
I'm closing this pull request because I have added the tests in a different manner.

**Pull request closed without merging**
